### ISSUE TITLE
Support full path for pid

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-monit#2]
Just ran into this trying to configure Monit for postfix. The pid for it is `/var/spool/postfix/pid/master.pid`. It's a bit of a hack, but you can configure it by doing:

``` yml
monit_postfix_process:
  pid: '../var/spool/postfix/pid/master.pid'
  process: 'postfix'
```

`monit_base_process_run_state` feels a bit weird in there. We can't overwrite it. Not sure if there's a way where we can only use it when we don't give a full path. I feel it should be assembled in a similar way as `monit_tpl_process`. Maybe something like this:

```
{% set monit_tpl_pid = item.pid %}
{% if not monit_tpl_pid | match('$/.*') %}
{% set monit_tpl_pid = monit_base_process_run_state + '/' + item.pid %}
{% endif %}
```

I'm not 100% sure of the best way to do this, but it's an idea lol.
